import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// NEW: Import ToastContainer and its CSS
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* NEW: Add ToastContainer here */}
        <ToastContainer 
          position="top-right" // Position of the toasts
          autoClose={3000}    // Toasts close after 3 seconds
          hideProgressBar={false} // Show or hide the progress bar
          newestOnTop={false}   // Newer toasts appear below older ones
          closeOnClick        // Close toast on click
          rtl={false}           // Right-to-left layout
          pauseOnFocusLoss    // Pause autoClose when window is out of focus
          draggable           // Allow dragging to dismiss
          pauseOnHover        // Pause autoClose on hover
        />
      </body>
    </html>
  );
}